### ISSUE TITLE
Esther: Remove unnecessary curly brackets from arrow fn & that nested semicolon 

### ISSUE THREAD

**Issue by daurham** [Gambit-FEC/Atelier#114]
https://github.com/Gambit-FEC/Atelier/blob/0ec293eb3e5cd512d348943ee9c20ec33d94e321/src/components/product-detail/add_to_cart/addButton.jsx#L13

**Comment by eghkuang** [comment]
Hi @daurham  ! ESLint does not like it when I do that so I think I'll keep it for now.
