### ISSUE TITLE
All: Consider refactoring arrow functions

### ISSUE THREAD

**Issue by daurham** [Gambit-FEC/Atelier#93]
Consider refactoring all cases where arrow functions run a single statement to:
```
 .then(() => res.sendStatus(203)) 
```
rather:
```
 .then(() => { 
   res.sendStatus(203); 
 }) 
```

https://github.com/Gambit-FEC/Atelier/blob/0ec293eb3e5cd512d348943ee9c20ec33d94e321/server/controllers/reviews.js#L65-L67

**Comment by gilcohen67** [comment]
- [ ]  Gil
- [ ]  Esther
- [ ]  Andy
